docs_dir: mkdocs-docs
site_name: teanga2

theme:
  name: "material"


nav:
  - index.md
  - reference.md
  - tutorials.md
  - how-to-guides.md
  - explanation.md

plugins:
  - search
  - gen-files:
      scripts:
        - mkdocs-docs/scripts/gen_pages.py  # or any other name or path
  - mkdocstrings:
     default_handler: python
