docs_dir: mkdocs-docs/src
site_name: teanga2
repo_url: https://github.com/TeangaNLP/teanga2
repo_name: TeangaNLP/teanga2


theme:
  name: "material"
  icon:
    repo: fontawesome/brands/git-alt
  logo: assets/images/teanga-logo.svg  # Add your logo image in the specified folder
  favicon: assets/images/favicon.ico  # Optional: set a favicon
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.tabs  # Enables the top navigation bar with tabs
    - header.autohide  # Makes the header autohide on scroll
    - content.code.annotate  # Annotated code blocks for more detailed explanations



nav:
  - index.md
  - Code Reference: 
    - teanga.corpus: reference/reference-corpus.md
    - teanga.document: reference/reference-document.md
    - teanga.groups: reference/reference-groups.md
    - reference.rdf: reference/reference-rdf.md  
    - reference.service: reference/reference-service.md 
    - reference.transforms: reference/reference-transforms.md
    - reference-utils: reference/reference-utils.md
  - Tutorials:
    - Getting Started: tutorials/getting-started.md
  - explanation.md

plugins:
  - search
  - mkdocstrings:
     default_handler: python
